num_envs: 300
num_eval_envs: 32
lr: 0.0003
max_it: 1000
max_grad_norm: 0.4
seed: 0
system_config: humanoid
demo_replay_mode: threshold
threshold: 0.4
normalize_observations: True
cycle_len: 60
ep_len: 60
ep_len_eval: 600
use_lr_scheduler: True
reward_scaling: 0.02
rot_weight: 0.5
vel_weight: 0.01
ang_weight: 0.01

ref: data/demo_humanoid/roll_fps_30_20s.npy
